### PR TITLE
Add support for Symfony 5

### PR DESCRIPTION
**Pull request by sebdesign**
- Drop support for Symfony <4.3
- Drop support for PHP <7.1

### CODE REVIEW

**Comment by stidges** [comment]
Sorry for bumping this! Would it be possible to get this PR merged? We're looking into upgrading our applications to the latest Laravel and this is blocking the upgrade because the framework relies on a newer Symfony version than this package supports

**Comment by mike182uk** [comment]
@sebdesign Thanks for your work on this, and sorry for the delay in looking at the PR!

The changes LGTM so i'll get this merged in and publish a new release 👍

**Comment by sebdesign** [comment]
Thanks for merging this @mike182uk !!

**Comment by mike182uk** [comment]
@sebdesign @stidges `v9.0.0` contains these changes 👍

**Comment by stidges** [comment]
Awesome, thanks!

**Pull request merged**
