### PR TITLE
[WIP] Replace Guzzle by HTTPlug

### LINKED ISSUE #21: Guzzle 6
Any plans for a Guzzle 6.x version? Thanks!

### PR DESCRIPTION
**Pull request by Lctrs**
Close #21.

TODO:
- [x] Update code
- [ ] Update tests
- [ ] Update doc

@mike182uk Do you have any feedbacks about it for the moment ?

### CODE REVIEW

**Comment by mablae** [comment]
I like the idea of using `OptionsResolver`

**Comment by matohavo** [comment]
+1

**Comment by mike182uk** [comment]
Hey @Lctrs, sorry for the late response to this, i haven't been around to check this out.

Ok, so quite a bit changes with your PR. From a skim i see you have done the following:

- **renamed events** - 👍  new naming makes sense
- **removed message object, pass data around as array instead** - Im not really a fan of passing around arrays, i would much prefer a value object to be passed around.
- **remove message factory and input stream factory stuff, use guessed stream factory**
- **pass config options to `ListenerBuilder` to dictate which http client etc. will be used**
- **`ListenerBuilder` attempts to guess client, message factory, stream factory** - How testable is this going to be? Where did you get the list of guessable compatible classes? Is this likely to change in the future?

Overall i am thinking this is a good change. It gets rid of some cruft and complexity. I am not sure how easy its going to be test these new changes though. We may need to split things up a bit more, but we can address that when it comes to it.

**Comment by Lctrs** [comment]
Hey @mike182uk,

> **removed message object, pass data around as array instead** - Im not really a fan of passing around arrays, i would much prefer a value object to be passed around.

Yeah that was one of the few things that didn't pleased me. I'll fix it.

> How testable is this going to be? Where did you get the list of guessable compatible classes? Is this likely to change in the future?

For this PR, I got my inspiration from https://github.com/Payum/Payum/pull/505 from which I got the list of guessable compatible classes.
This can change if they change namespaces of these classes in the future (But we are protected from it since they follow SemVer).

Other things I'm going to rework :

- Remove dependency to guzzle/psr7
- Add more functions to Verifier class to be more testable

**Comment by mablae** [comment]
Nice to see the improvements! Looks like a new major when ready. :+1:

**Comment by mablae** [comment]
@Lctrs Any updates on this? I am also running in version conflicts with Guzzle6

**Comment by Lctrs** [comment]
I'll try to continue the work on this tonight.

**Comment by mablae** [comment]
:+1:  Just let me know I can help testing or anything else. I am idling on freenode and twitter.

**Comment by Lctrs** [comment]
IMHO, I have finished to update code.

@mike182uk, @mablae, any feedbacks ?

Do you have any opinions on how to test it ?

**Comment by mike182uk** [comment]
@Lctrs I've just had another look, some feedback:

- We discussed above about not passing arrays around, instead using a value object similar to how it was originally. This object was originally called `Message` and was created by a `MessageFactory`. It looks like these are conflicting terms with the HTTP clients, so maybe we should call the value object `Notification`?
- Currently the data is being pulled from the input stream. In my original implementation i had the concept of a `MessageFactory` and a `Message` could be created either from the input stream or from an array. I would still like to keep this functionality (creating a `Message` from an array) which means we are still going to need the `MessageFactory` (or `NotificationFactory` if we named the value object `Notification`)
- The stream creation logic [here](https://github.com/mike182uk/paypal-ipn-listener/pull/26/files#diff-1c3b5b26a3c911db21c408525577797dR100) could be extracted to separate class, i don't think this logic belongs in the `Listener` class (maybe it would be better as part of the `NotificationFactory` mentioned above?)
- The query parsing logic [here](https://github.com/mike182uk/paypal-ipn-listener/pull/26/files#diff-1c3b5b26a3c911db21c408525577797dR123) could be extracted to separate class, i don't think this logic belongs in the `Listener` class.
- The query building logic [here](https://github.com/mike182uk/paypal-ipn-listener/pull/26/files#diff-005d5addb0326cd7b0ecd0ac6bfde672R79) could be extracted to separate class, i don't think this logic belongs in the `Verifier` class.
- What was the reason for implement the query parsing / building logic yourself instead of using `guzzlehttp/psr7`?
- After a bit of thinking, i am not sure i am keen on the guessing of dependencies [here](https://github.com/mike182uk/paypal-ipn-listener/pull/26/files#diff-11957afbd10f799a102d418b225a1ebaR24). I think it would be better that the user was explicit about the dependencies they wanted to use. As it is, i' am pretty sure its going to be impossible to test and it creates a bit of a maintenance headache when new dependencies could be used, old ones need to be removed etc.

**Comment by mike182uk** [comment]
@mablae I've just tagged a new version that uses the latest version of guzzle

**Comment by mablae** [comment]
@mike182uk Thank you! 

@Lctrs Smaller chunks wound be better for future merges. This is like a new library :smile: 
In general it look like many tests could be removed, some needs adaption to new structure.

But @mike182uk Feedback is far more detailed then mine :+1:

**Comment by Lctrs** [comment]
Will close this for now. Sorry to haven't taken the time to finish that, but my company changed their plans and we ended up not using your library, so my motivation quite fall a bit.

**Pull request closed without merging**
